version: "3"
services:
  bode:
    build: ./bode
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    env_file:
      - .env.example
      - .env
    volumes:
      - ./bode:/bode/

  cabra:
    build: ./cabra
    depends_on:
      - bode
    ports:
      - "3000:3000"
    env_file:
      - .env.example
    volumes:
      - ./cabra:/cabra/

  postgres:
    image: postgres:latest
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    env_file:
      - .env.example
    ports:
      - "5432:5432"

volumes:
  postgres-data:
