FROM python:3.10.4

WORKDIR /app

COPY bode/pyproject.toml bode/poetry.lock /app/

RUN pip3 install poetry==1.1.13
RUN poetry config virtualenvs.create false
RUN poetry install

COPY bode /app

CMD FLASK_APP=bode/app.py flask db upgrade