FROM node:16.14.2 as cabra-builder

COPY cabra/package.json cabra/package-lock.json /

RUN npm ci

COPY cabra /

RUN npm run build

FROM python:3.10.4

WORKDIR /app

COPY bode/pyproject.toml bode/poetry.lock /app/

RUN pip3 install poetry==1.1.13
RUN poetry config virtualenvs.create false
RUN poetry install

COPY bode /app

RUN mkdir static

COPY --from=cabra-builder /dist /app/static

CMD gunicorn 'bode.app:create_app()' --bind 0.0.0.0:$PORT