"""Add rrule field to task model

Revision ID: 2a4d3f982d82
Revises: 5c592f0ac54b
Create Date: 2022-06-02 16:33:11.590869

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2a4d3f982d82"
down_revision = "5c592f0ac54b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("rrule", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "rrule")
    # ### end Alembic commands ###
