"""Add notification time to task model

Revision ID: 4a5040ab3b05
Revises: 4bf1c662e32d
Create Date: 2022-06-18 18:41:42.605272

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4a5040ab3b05"
down_revision = "4bf1c662e32d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("notify_before_minutes", sa.Integer(), nullable=True))
    op.create_check_constraint("positive_notify_before_minutes", "tasks", "notify_before_minutes > 0")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("positive_notify_before_minutes", "tasks")
    op.drop_column("tasks", "notify_before_minutes")
    # ### end Alembic commands ###
