"""Add notifications data model

Revision ID: 4bf1c662e32d
Revises: 5325b3a47498
Create Date: 2022-06-18 17:20:05.928975

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4bf1c662e32d"
down_revision = "5325b3a47498"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications_data",
        sa.Column("id", sa.String(length=256), nullable=False, server_default="notifications_data"),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(timezone=False), nullable=True),
        sa.CheckConstraint("id = 'notifications_data'", name="single_row_check"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute("INSERT INTO notifications_data (email, last_sent_at) VALUES (NULL, NULL) ON CONFLICT DO NOTHING")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("notifications_data")
    # ### end Alembic commands ###
