"""Use task status

Revision ID: 4c05d8b56a2d
Revises: d71419c8a49a
Create Date: 2022-05-02 19:55:23.069770

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4c05d8b56a2d"
down_revision = "d71419c8a49a"
branch_labels = None
depends_on = None

status = postgresql.ENUM("todo", "indirectly_done", "done", name="status")


def upgrade():
    status.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "status", sa.Enum("todo", "indirectly_done", "done", name="status"), server_default="todo", nullable=False
        ),
    )
    op.drop_column("tasks", "is_done")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("is_done", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "status")
    # ### end Alembic commands ###
    status.drop(op.get_bind())
