"""Use task status

Revision ID: 5c592f0ac54b
Revises: d71419c8a49a
Create Date: 2022-05-05 21:13:36.734542

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c592f0ac54b"
down_revision = "d71419c8a49a"
branch_labels = None
depends_on = None


task_status = postgresql.ENUM("TODO", "INDIRECTLY_DONE", "DONE", name="task_status")


def upgrade():
    task_status.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "status",
            sa.Enum("TODO", "INDIRECTLY_DONE", "DONE", name="task_status"),
            server_default="TODO",
            nullable=False,
        ),
    )
    op.drop_column("tasks", "is_done")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("is_done", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "status")
    # ### end Alembic commands ###
    task_status.drop(op.get_bind())
