"""add recurring tasks

Revision ID: 67993210b2c4
Revises: 5c592f0ac54b
Create Date: 2022-06-03 13:43:46.345455

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "67993210b2c4"
down_revision = "5c592f0ac54b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recurring_tasks",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=False), nullable=True),
        sa.Column("status", postgresql.ENUM(name="task_status", create_type=False), nullable=True),
        sa.Column("main_task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("instance_key", sa.String(length=64), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["main_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recurring_tasks")
    # ### end Alembic commands ###
