"""Add column is_done to model

Revision ID: 903de4e9cee5
Revises: 9b8806b556b8
Create Date: 2022-04-07 13:48:56.613488

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "903de4e9cee5"
down_revision = "9b8806b556b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("is_done", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "is_done")
    # ### end Alembic commands ###
