"""Add due date and description to task model

Revision ID: 9b8806b556b8
Revises: 4daafbe3fd77
Create Date: 2022-04-03 19:53:56.792053

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b8806b556b8"
down_revision = "4daafbe3fd77"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "description",
            sa.String(length=1024),
            server_default="",
            nullable=False,
        ),
    )
    op.add_column(
        "tasks",
        sa.Column("due_date", sa.DateTime(timezone=False), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "due_date")
    op.drop_column("tasks", "description")
    # ### end Alembic commands ###
