"""Add task relations model

Revision ID: bf275b0792b8
Revises: 903de4e9cee5
Create Date: 2022-04-11 20:40:10.160859

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bf275b0792b8"
down_revision = "903de4e9cee5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks_relations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("first_task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("second_task_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "DEPENDENT",
                "INTERCHANGABLE",
                "SUBTASK",
                name="task_relation_type",
            ),
            nullable=False,
        ),
        sa.CheckConstraint("first_task_id <> second_task_id", name="self_relation_check"),
        sa.ForeignKeyConstraint(
            ["first_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "task_relations_index",
        "tasks_relations",
        ["first_task_id", "second_task_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("task_relations_index", table_name="tasks_relations")
    op.drop_table("tasks_relations")
    # ### end Alembic commands ###
    op.execute("DROP TYPE task_relation_type")
