name: "Bode CI"

on:
  pull_request:
    paths:
      - "bode/**"
  push:
    paths:
      - "bode/**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bode

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.13"

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2
        env:
          cache-name: cache-venv
        with:
          path: .venv
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Check formatting
        run: poetry run black bode migrations --check --verbose

      - name: Lint
        run: poetry run flake8 bode migrations --verbose

      - name: Check sorting
        run: poetry run isort bode migrations --check
