name: "Deploy"

on:
  release:
    types: [published]

jobs:
  deploy-bode:
    name: "Deploy Bode to Heroku"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jctaveras/heroku-deploy@v3.1.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: "."
          process_type: "web release"

  deploy-cabra:
    name: "Deploy Cabra to Netlify"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cabra
    env:
      CABRA_API_URL: ${{ secrets.NETLIFY_API_URL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - uses: nwtgck/actions-netlify@v1.2.3
        with:
          publish-dir: "cabra/dist"
          production-branch: master
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
